#include "pwm.h"

#define PWMA_ETRPS (*(__xdata volatile unsigned char *) 0xFEB0)
#define PWMA_ENO (*(__xdata volatile unsigned char *) 0xFEB1)
#define PWMA_PS (*(__xdata volatile unsigned char *) 0xFEB2)
#define PWMA_IOAUX (*(__xdata volatile unsigned char *) 0xFEB3)
#define PWMA_CR1 (*(__xdata volatile unsigned char *) 0xFEC0)
#define PWMA_CR2 (*(__xdata volatile unsigned char *) 0xFEC1)
#define PWMA_SMCR (*(__xdata volatile unsigned char *) 0xFEC2)
#define PWMA_ETR (*(__xdata volatile unsigned char *) 0xFEC3)
#define PWMA_IER (*(__xdata volatile unsigned char *) 0xFEC4)
#define PWMA_SR1 (*(__xdata volatile unsigned char *) 0xFEC5)
#define PWMA_SR2 (*(__xdata volatile unsigned char *) 0xFEC6)
#define PWMA_EGR (*(__xdata volatile unsigned char *) 0xFEC7)
#define PWMA_CCMR1 (*(__xdata volatile unsigned char *) 0xFEC8)
#define PWMA_CCMR2 (*(__xdata volatile unsigned char *) 0xFEC9)
#define PWMA_CCMR3 (*(__xdata volatile unsigned char *) 0xFECA)
#define PWMA_CCMR4 (*(__xdata volatile unsigned char *) 0xFECB)
#define PWMA_CCER1 (*(__xdata volatile unsigned char *) 0xFECC)
#define PWMA_CCER2 (*(__xdata volatile unsigned char *) 0xFECD)
#define PWMA_CNTR (*(__xdata volatile unsigned int *) 0xFECE)
#define PWMA_CNTRH (*(__xdata volatile unsigned char *) 0xFECE)
#define PWMA_CNTRL (*(__xdata volatile unsigned char *) 0xFECF)
#define PWMA_PSCR (*(__xdata volatile unsigned int *) 0xFED0)
#define PWMA_PSCRH (*(__xdata volatile unsigned char *) 0xFED0)
#define PWMA_PSCRL (*(__xdata volatile unsigned char *) 0xFED1)
#define PWMA_ARR (*(__xdata volatile unsigned int *) 0xFED2)
#define PWMA_ARRH (*(__xdata volatile unsigned char *) 0xFED2)
#define PWMA_ARRL (*(__xdata volatile unsigned char *) 0xFED3)
#define PWMA_RCR (*(__xdata volatile unsigned char *) 0xFED4)
#define PWMA_CCR1 (*(__xdata volatile unsigned int *) 0xFED5)
#define PWMA_CCR1H (*(__xdata volatile unsigned char *) 0xFED5)
#define PWMA_CCR1L (*(__xdata volatile unsigned char *) 0xFED6)
#define PWMA_CCR2 (*(__xdata volatile unsigned int *) 0xFED7)
#define PWMA_CCR2H (*(__xdata volatile unsigned char *) 0xFED7)
#define PWMA_CCR2L (*(__xdata volatile unsigned char *) 0xFED8)
#define PWMA_CCR3 (*(__xdata volatile unsigned int *) 0xFED9)
#define PWMA_CCR3H (*(__xdata volatile unsigned char *) 0xFED9)
#define PWMA_CCR3L (*(__xdata volatile unsigned char *) 0xFEDA)
#define PWMA_CCR4 (*(__xdata volatile unsigned int *) 0xFEDB)
#define PWMA_CCR4H (*(__xdata volatile unsigned char *) 0xFEDB)
#define PWMA_CCR4L (*(__xdata volatile unsigned char *) 0xFEDC)
#define PWMA_BRK (*(__xdata volatile unsigned char *) 0xFEDD)
#define PWMA_DTR (*(__xdata volatile unsigned char *) 0xFEDE)
#define PWMA_OISR (*(__xdata volatile unsigned char *) 0xFEDF)

void pwm_init(void) {
    // TODO
}